### ISSUE TITLE
Can't generate output file normally 

### ISSUE THREAD

**Issue by forestbat** [opengeos/whitebox-python#70]
* whitebox version: 2.3.4
* Python version: 3.11.9
* Operating System: ubuntu 20.04

I want to extract `d8 flow direction` from my DEM file, and my file's path is:
```
/home/username/interim_dir/tests/merged_hjlm.tif
```
So I wrote this code:
```
dem = 'merged_hjlm.tif'
wbt = whitebox.WhiteboxTools()
# working_dir is /home/username/interim_dir/tests
wbt.set_working_dir(pathlib.Path(dem).parent.absolute())
wbt.fill_missing_data(i=dem, output="fillmissingdata.tif", filter=11, weight=2.0, no_edges=True)
wbt.fill_depressions_wang_and_liu("fillmissingdata.tif", "filldepression.tif", fix_flats=True, flat_increment=None,  # max_depth=None)
wbt.d8_pointer("filldepression.tif", "d8pointer.tif", esri_pntr=False)
```
However this process ended unnormally, and log is:
```
================== 1 passed, 3 warnings in 594.59s (0:09:54) ===================
./whitebox_tools --run="FillMissingData" --wd="/home/username/interim_dir/tests" --input='merged_hjlm.tif' --output='fillmissingdata.tif' --filter=11 --weight=2.0 --no_edges -v --compress_rasters=False

******************************
* Welcome to FillMissingData *
* Powered by WhiteboxTools   *
* www.whiteboxgeo.com        *
******************************
Reading data...
./whitebox_tools --run="FillDepressionsWangAndLiu" --wd="/home/username/interim_dir/tests" --dem='fillmissingdata.tif' --output='filldepression.tif' --fix_flats -v --compress_rasters=False

****************************************
* Welcome to FillDepressionsWangAndLiu *
* Powered by WhiteboxTools             *
* www.whiteboxgeo.com                  *
****************************************
Reading data...
thread 'main' panicked at whitebox-tools-app/src/main.rs:72:21:
No such file or directory (os error 2)
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
./whitebox_tools --run="D8Pointer" --wd="/home/username/interim_dir/tests" --dem='filldepression.tif' --output='d8pointer.tif' -v --compress_rasters=False

****************************
* Welcome to D8Pointer     *
* Powered by WhiteboxTools *
* www.whiteboxgeo.com      *
****************************
Reading data...
thread 'main' panicked at whitebox-tools-app/src/main.rs:72:21:
No such file or directory (os error 2)
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
You can see `fillmissingdata.tif` isn't generated in my working dir so following steps can't run.
How to solve the problem? Hope for your reply.

**Comment by giswqs** [comment]
This is likely an issue with the GeoTIFF you are using. Try it with the test dataset below. If it work but not your own data, that means your GeoTIFF is not supported by whitebox. Try using a GeoTIFF without compression

https://github.com/opengeos/whitebox-python/tree/master/examples/testdata

**Comment by jblindsay** [comment]
I don't think that it can be an unsupported GeoTIFF format issue Qiusheng. Whitebox is issuing an 'No such file or directory (os error 2)' error, so it's more likely a matter of the file is not where it's looking for it. Are you quite certain that `filldepression.tif` is located in `/home/username/interim_dir/tests`?

**Comment by giswqs** [comment]
@jblindsay You are right. It seems a filepath issue. @forestbat Try using the absolute filepath as the input.

**Comment by forestbat** [comment]
@jblindsay @giswqs 

I downloaded testdata(DEM.tif) and run my code, it's correct. And it looks like my tiff file is wrong.

My `dem` file is merged by rasterio:
```(python)
file_paths = glob.glob('/ftproot/dems/*.hgt', recursive=True)
datasets = [rasterio.open(file_path) for file_path in file_paths]
out_img, out_transform = merge(datasets)
with rasterio.open('merged_hjlm.tif', 'w', width=out_img.shape[2], height=out_img.shape[1],
                           count=1, crs='EPSG:4326', transform=out_transform, dtype='int16', nodata=-32768, compress='lzw') as dest:
        dest.write(out_img)
```
No I will try wbt.mosaic to merge them.
